//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwitchGiftDataManager.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwitchGiftDataManager.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tops
        ///Outerwear
        ///Pikachu Hoodie Style
        ///Platinum Style
        ///Overalls Style
        ///Eevee Jacket Style
        ///Cyber Style
        ///Summer Style
        ///Winter Style
        ///Spring Style
        ///Casual Style
        ///Leather Jacket Style
        ///Contest Style
        ///Gengar Jacket Style
        ///Everyday Style
        ///.
        /// </summary>
        internal static string BDSPClothing {
            get {
                return ResourceManager.GetString("BDSPClothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None
        ///Master Ball
        ///Ultra Ball
        ///Great Ball
        ///Poké Ball
        ///Safari Ball
        ///Net Ball
        ///Dive Ball
        ///Nest Ball
        ///Repeat Ball
        ///Timer Ball
        ///Luxury Ball
        ///Premier Ball
        ///Dusk Ball
        ///Heal Ball
        ///Quick Ball
        ///Cherish Ball
        ///Potion
        ///Antidote
        ///Burn Heal
        ///Ice Heal
        ///Awakening
        ///Paralyze Heal
        ///Full Restore
        ///Max Potion
        ///Hyper Potion
        ///Super Potion
        ///Full Heal
        ///Revive
        ///Max Revive
        ///Fresh Water
        ///Soda Pop
        ///Lemonade
        ///Moomoo Milk
        ///Energy Powder
        ///Energy Root
        ///Heal Powder
        ///Revival Herb
        ///Ether
        ///Max Ether
        ///Elixir
        ///Max Elixir
        ///Lava Cookie
        ///Berry Juice [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Fancy Bottoms (Oshawott)
        ///Fancy Bottoms (Cyndaquil)
        ///Fancy Bottoms (Rowlet)
        ///Fancy Bottoms (Typhlosion)
        ///Fancy Bottoms (Samurott)
        ///Fancy Bottoms (Decidueye)
        ///Fancy Bottoms (Gyarados)
        ///Fancy Bottoms (Cherrim)
        ///Fancy Bottoms (Seascape)
        ///Fancy Bottoms (Mountainscape)
        ///Fancy Bottoms (Townscape)
        ///Fancy Bottoms (Spiritomb)
        ///Fancy Bottoms (Honchkrow [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PLAClothingBottoms {
            get {
                return ResourceManager.GetString("PLAClothingBottoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Baneful Fox Mask (White lily)
        ///Baneful Fox Mask (Shiny)
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PLAClothingHeads {
            get {
                return ResourceManager.GetString("PLAClothingHeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///Fancy Kimono (Oshawott)
        ///Fancy Kimono (Cyndaquil)
        ///Fancy Kimono (Rowlet)
        ///Fancy Kimono (Typhlosion)
        ///Fancy Kimono (Samurott)
        ///Fancy Kimono (Decidueye)
        ///Fancy Kimono (Gyarados)
        ///Fancy Kimono (Cherrim)
        ///Fancy Kimono (Seascape)
        ///Fancy Kimono (Mountainscape)
        ///Fancy Kimono (Townscape)
        ///Fancy Kimono (Spiritomb)
        ///Fancy Kimono (Honchkrow)
        ///Fancy Kimo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PLAClothingTops {
            get {
                return ResourceManager.GetString("PLAClothingTops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SCVIClothings {
            get {
                return ResourceManager.GetString("SCVIClothings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None,
        ///Bulbasaur,
        ///Ivysaur,
        ///Venusaur,
        ///Charmander,
        ///Charmeleon,
        ///Charizard,
        ///Squirtle,
        ///Wartortle,
        ///Blastoise,
        ///Caterpie,
        ///Metapod,
        ///Butterfree,
        ///Weedle,
        ///Kakuna,
        ///Beedrill,
        ///Pidgey,
        ///Pidgeotto,
        ///Pidgeot,
        ///Rattata,
        ///Raticate,
        ///Spearow,
        ///Fearow,
        ///Ekans,
        ///Arbok,
        ///Pikachu,
        ///Raichu,
        ///Sandshrew,
        ///Sandslash,
        ///NidoranF,
        ///Nidorina,
        ///Nidoqueen,
        ///NidoranM,
        ///Nidorino,
        ///Nidoking,
        ///Clefairy,
        ///Clefable,
        ///Vulpix,
        ///Ninetales,
        ///Jigglypuff,
        ///Wigglytuff,
        ///Zubat,
        ///Golbat,
        ///Oddish,
        ///Gloom,
        ///Vileplume,
        ///Paras,
        ///Parasect,
        ///Venon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Species {
            get {
                return ResourceManager.GetString("Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport Travel Bag (Iconic Style)
        ///Sport Travel Bag (Challenger Kit)
        ///Sport Travel Bag (Grass Type)
        ///Sport Travel Bag (Water Type)
        ///Sport Travel Bag (Fire Type)
        ///Sport Travel Bag (Ghost Type)
        ///Sport Travel Bag (Fighting Type)
        ///Sport Travel Bag (Fairy Type)
        ///Sport Travel Bag (Rock Type)
        ///Sport Travel Bag (Ice Type)
        ///Sport Travel Bag (Dark Type)
        ///Sport Travel Bag (Dragon Type)
        ///Sport Travel Bag (Bug Type)
        ///Sport Travel Bag (Steel Type)
        ///Sport Travel Bag (Psychic Type)
        ///Sport Travel Bag (Electric Type)
        ///Sport Tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWSHClothingBags {
            get {
                return ResourceManager.GetString("SWSHClothingBags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport Shorts (Challenger Kit)
        ///Sport Shorts (Grass Type)
        ///Sport Shorts (Water Type)
        ///Sport Shorts (Fire Type)
        ///Sport Shorts (Ghost Type)
        ///Sport Shorts (Fighting Type)
        ///Sport Shorts (Fairy Type)
        ///Sport Shorts (Rock Type)
        ///Sport Shorts (Ice Type)
        ///Sport Shorts (Dark Type)
        ///Sport Shorts (Dragon Type)
        ///Sport Shorts (Bug Type)
        ///Sport Shorts (Steel Type)
        ///Sport Shorts (Psychic Type)
        ///Sport Shorts (Electric Type)
        ///Sport Shorts (Ground Type)
        ///Sport Shorts (Flying Type)
        ///Sport Shorts (Normal Type)
        ///Sport Shorts (Poi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWSHClothingBottoms {
            get {
                return ResourceManager.GetString("SWSHClothingBottoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport Sunglasses (Iconic Style)
        ///Sport Sunglasses (Challenger Kit)
        ///Sport Sunglasses (Grass Type)
        ///Sport Sunglasses (Water Type)
        ///Sport Sunglasses (Fire Type)
        ///Sport Sunglasses (Ghost Type)
        ///Sport Sunglasses (Fighting Type)
        ///Sport Sunglasses (Fairy Type)
        ///Sport Sunglasses (Rock Type)
        ///Sport Sunglasses (Ice Type)
        ///Sport Sunglasses (Dark Type)
        ///Sport Sunglasses (Dragon Type)
        ///Sport Sunglasses (Bug Type)
        ///Sport Sunglasses (Steel Type)
        ///Sport Sunglasses (Psychic Type)
        ///Sport Sunglasses (Electric Type)
        ///Sport Su [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWSHClothingGlasses {
            get {
                return ResourceManager.GetString("SWSHClothingGlasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (empty) (Bare)
        ///Sport Glove (Challenger Kit)
        ///Sport Glove (Grass Type)
        ///Sport Glove (Water Type)
        ///Sport Glove (Fire Type)
        ///Sport Glove (Ghost Type)
        ///Sport Glove (Fighting Type)
        ///Sport Glove (Fairy Type)
        ///Sport Glove (Rock Type)
        ///Sport Glove (Ice Type)
        ///Sport Glove (Dark Type)
        ///Sport Glove (Dragon Type)
        ///Sport Glove (Bug Type)
        ///Sport Glove (Steel Type)
        ///Sport Glove (Psychic Type)
        ///Sport Glove (Electric Type)
        ///Sport Glove (Ground Type)
        ///Sport Glove (Flying Type)
        ///Sport Glove (Normal Type)
        ///Sport Glove (Poison [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWSHClothingGloves {
            get {
                return ResourceManager.GetString("SWSHClothingGloves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport Cap (Iconic Style)
        ///Sport Cap (Challenger Kit)
        ///Sport Cap (Grass Type)
        ///Sport Cap (Water Type)
        ///Sport Cap (Fire Type)
        ///Sport Cap (Ghost Type)
        ///Sport Cap (Fighting Type)
        ///Sport Cap (Fairy Type)
        ///Sport Cap (Rock Type)
        ///Sport Cap (Ice Type)
        ///Sport Cap (Dark Type)
        ///Sport Cap (Dragon Type)
        ///Sport Cap (Bug Type)
        ///Sport Cap (Steel Type)
        ///Sport Cap (Psychic Type)
        ///Sport Cap (Electric Type)
        ///Sport Cap (Ground Type)
        ///Sport Cap (Flying Type)
        ///Sport Cap (Normal Type)
        ///Sport Cap (Poison Type)
        ///Scally Cap (White)
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWSHClothingHats {
            get {
                return ResourceManager.GetString("SWSHClothingHats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracksuit Jacket (Iconic Style)
        ///Tracksuit Jacket (Challenger Kit)
        ///Tracksuit Jacket (Grass Type)
        ///Tracksuit Jacket (Water Type)
        ///Tracksuit Jacket (Fire Type)
        ///Tracksuit Jacket (Ghost Type)
        ///Tracksuit Jacket (Fighting Type)
        ///Tracksuit Jacket (Fairy Type)
        ///Tracksuit Jacket (Rock Type)
        ///Tracksuit Jacket (Ice Type)
        ///Tracksuit Jacket (Dark Type)
        ///Tracksuit Jacket (Dragon Type)
        ///Tracksuit Jacket (Bug Type)
        ///Tracksuit Jacket (Steel Type)
        ///Tracksuit Jacket (Psychic Type)
        ///Tracksuit Jacket (Electric Type)
        ///Tracksui [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWSHClothingJackets {
            get {
                return ResourceManager.GetString("SWSHClothingJackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport Legwear (Challenger Kit)
        ///Sport Legwear (Grass Type)
        ///Sport Legwear (Water Type)
        ///Sport Legwear (Fire Type)
        ///Sport Legwear (Ghost Type)
        ///Sport Legwear (Fighting Type)
        ///Sport Legwear (Fairy Type)
        ///Sport Legwear (Rock Type)
        ///Sport Legwear (Ice Type)
        ///Sport Legwear (Dark Type)
        ///Sport Legwear (Dragon Type)
        ///Sport Legwear (Bug Type)
        ///Sport Legwear (Steel Type)
        ///Sport Legwear (Psychic Type)
        ///Sport Legwear (Electric Type)
        ///Sport Legwear (Ground Type)
        ///Sport Legwear (Flying Type)
        ///Sport Legwear (Normal Type)        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWSHClothingLegwear {
            get {
                return ResourceManager.GetString("SWSHClothingLegwear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport High-Tops (Challenger Kit)
        ///Sport High-Tops (Grass Type)
        ///Sport High-Tops (Water Type)
        ///Sport High-Tops (Fire Type)
        ///Sport High-Tops (Ghost Type)
        ///Sport High-Tops (Fighting Type)
        ///Sport High-Tops (Fairy Type)
        ///Sport High-Tops (Rock Type)
        ///Sport High-Tops (Ice Type)
        ///Sport High-Tops (Dark Type)
        ///Sport High-Tops (Dragon Type)
        ///Sport High-Tops (Bug Type)
        ///Sport High-Tops (Steel Type)
        ///Sport High-Tops (Psychic Type)
        ///Sport High-Tops (Electric Type)
        ///Sport High-Tops (Ground Type)
        ///Sport High-Tops (Flying T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWSHClothingShoes {
            get {
                return ResourceManager.GetString("SWSHClothingShoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport Top (Challenger Kit)
        ///Sport Top (Grass Type)
        ///Sport Top (Water Type)
        ///Sport Top (Fire Type)
        ///Sport Top (Ghost Type)
        ///Sport Top (Fighting Type)
        ///Sport Top (Fairy Type)
        ///Sport Top (Rock Type)
        ///Sport Top (Ice Type)
        ///Sport Top (Dark Type)
        ///Sport Top (Dragon Type)
        ///Sport Top (Bug Type)
        ///Sport Top (Steel Type)
        ///Sport Top (Psychic Type)
        ///Sport Top (Electric Type)
        ///Sport Top (Ground Type)
        ///Sport Top (Flying Type)
        ///Sport Top (Normal Type)
        ///Sport Top (Poison Type)
        ///Sport Top (Reigning Champion)
        ///Sport Top (Pika [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SWSHClothingTops {
            get {
                return ResourceManager.GetString("SWSHClothingTops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None
        ///Red Sphere S
        ///Blue Sphere S
        ///Green Sphere S
        ///Prism Sphere S
        ///Pale Sphere S
        ///Red Sphere L
        ///Blue Sphere L
        ///Green Sphere L
        ///Prism Sphere L
        ///Pale Sphere L
        ///Revive
        ///Max Revive
        ///Red Shard
        ///Blue Shard
        ///Yellow Shard
        ///Green Shard
        ///Sun Stone
        ///Moon Stone
        ///Fire Stone
        ///Thunder Stone
        ///Water Stone
        ///Leaf Stone
        ///Oval Stone
        ///Everstone
        ///Odd Keystone
        ///Star Piece
        ///Heart Scale
        ///Root Fossil
        ///Claw Fossil
        ///Helix Fossil
        ///Dome Fossil
        ///Old Amber
        ///Armor Fossil
        ///Skull Fossil
        ///Rare Bone
        ///Light Clay
        ///Iron Ball
        ///Icy Rock
        ///Smooth Rock [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UndergroundItems {
            get {
                return ResourceManager.GetString("UndergroundItems", resourceCulture);
            }
        }
    }
}
